### ISSUE TITLE
Dynamic tag

### ISSUE THREAD

**Issue by danhper** [gabrielmoreira/riot-router#11]
Hi,

Here is what I am trying to achieve: show a dashboard when the user is logged in,
and a landing page when the user is not, both on the root path (so the router top `DefaultRoute`).
This is I think a pretty common use case, used by a lot of webservices, starting by this one.

I am not aware of any way to implement this with the current library. I think it could have
been implemented with the [old `redirect` behavior](https://github.com/gabrielmoreira/riot-router/issues/8) but I think this would have been kind of an anti-pattern anyway.

An easy way of implementing this could be to accept a function for the `tag` property
of the routes. The function could possibly be evaluated in the `route` tag `mountTag` method,
I think that this should give enough flexibility to handle most use cases without adding too
much complexity. The only change would probably be to avoid that `tag` is used as the path when
it is provided as a function.

This would allow to write something like

``` javascript
new router.DefaultRoute({
  tag: function () {
    if (user.loggedIn()) {
      return 'dashboard';
    } else {
      return 'landing';
    }
})
```

What do you think about this?

**Comment by gabrielmoreira** [comment]
Hi @tuvistavie,

We need to think carefully about it. It looks cool, but we have to think of the impacts.

Today you can have a similar behavior by doing the following:

1) If you want safe routes, you can use the middleware feature to intercept the access and redirect to a login page.

2) If you want a page has different behavior, you could use the riot-if within the tag.

It seems simpler using dynamic tags, but this only solves the security of a single tag / route. Also, we have to see how to get the api attribute that should also be dynamic within tag.

What do you think?

One question: If user log in using AJAX, how the router will track and reevaluate current route / tag?

**Comment by danhper** [comment]
Hi @gabrielmoreira,

Thanks for the quick reply.
1. I do not think that this should ever be used for security purposes.
2. This is the alternative I am currently using, but I think it is not very clean to have a tag to add a simple condition, and it makes the route pretty unclear about what it is going to render, so I thought that having this directly in the router would be a better approach.

The closest thing I know about for frontend routers is the [dynamic template feature of AngularJS ui router](https://github.com/angular-ui/ui-router/wiki#templates), although the design is a bit too different to be compared.

> It seems simpler using dynamic tags, but this only solves the security of a single tag / route. 

As I said in 1, this is definitely not a security feature, but rather a feature to keep clean URLs
and an expressive routing layer.

> Also, we have to see how to get the api attribute that should also be dynamic within tag.

For the api attributes, it should not be too hard to accept a function, but I do not see a good use case for it yet. Do you have something in mind?
Another possibility, as the tag and `api` object usually come in pair, would be to allow different return types for `tag` when passed as a function. For example, it could either return the tag name as a string, or an object of the form `{tag: TAG_NAME, api: {some: 'data'}}` when api need to be dynamic.

> If user log in using AJAX, how the router will track and reevaluate current route / tag?

I think we should leave this up to the user. Triggering `route:updated` should be enough.
Maybe providing a `router.update` to do so would be more intuitive.

I am going to implement it and give it a shot in my current project.
If I think it is good enough I will send a PR so we can discuss there,
otherwise I will let you know what went wrong here.

**Comment by gabrielmoreira** [comment]
Hi @tuvistavie,

1) Ok, clean URLs is a good use case. 

2) I think returning string is enough for a while. But i liked returning a string or an object `{tag, api}`.

3) Reevaluations can be done with `riot.router.exec()`

4) I will wait your PR.

Thanks!

**Comment by danhper** [comment]
Hi @gabrielmoreira,

I just sent a PR, take a look when you have time.

> 3) Reevaluations can be done with riot.router.exec()

This worked perfectly for me, thanks.

**Comment by gabrielmoreira** [comment]
@tuvistavie,

Riot-Router 0.7.1 released.

**Comment by danhper** [comment]
Great, thanks!
