### ISSUE TITLE
Router does not show Home page on start

### ISSUE THREAD

**Issue by AlexRadch** [gabrielmoreira/riot-router#16]
Why router does not show Home page on start?
http://plnkr.co/edit/OAnEIBi9SwYgTSQDeGp8?p=preview

Only when I select Home page at menu.

**Comment by gabrielmoreira** [comment]
Hi,
with riot+compiler.js you must use `riot.compile(function() { ... mount here ... });` when loading riot scripts with src.
http://riotjs.com/guide/compiler/#access-tag-instances

**Comment by gabrielmoreira** [comment]
Test here:
http://plnkr.co/edit/fd4ryZreukzNcar3J7Lm?p=preview
