### ISSUE TITLE
Riot-router does not work in Chrome browser

### ISSUE THREAD

**Issue by AlexRadch** [gabrielmoreira/riot-router#20]
It works in Firefox browser.
It does not work in Chrome browser.
Open example in both browsers http://plnkr.co/edit/OAnEIBi9SwYgTSQDeGp8?p=preview

**Comment by gabrielmoreira** [comment]
@AlexRadch , raw.githubcontent is serving files with content-type text/plain.
just change from 

```
<script src="https://raw.githubusercontent.com/gabrielmoreira/riot-router/master/lib/router.min.js"></script>
```

to 

```
<script src="http://gabrielmoreira.github.io/riot-router/examples/node_modules/riot-router/lib/router.min.js"></script>
```

**Comment by AlexRadch** [comment]
@gabrielmoreira, thank you!

I found https://rawgit.com/ and I just replace `https://raw.githubusercontent.com/gabrielmoreira/riot-router/master/lib/router.min.js` with `https://rawgit.com/gabrielmoreira/riot-router/master/lib/router.min.js`
