### ISSUE TITLE
URL History Access.

### ISSUE THREAD

**Issue by hibiarata** [gabrielmoreira/riot-router#27]
Hi gabriel.
Does riot-router have any methods to access url history?

hibiarata

**Comment by gabrielmoreira** [comment]
@hibiarata No. Only the current uri.

But you can try something like: 
https://plnkr.co/edit/9AO1q6KGijpJX6LbenLT?p=preview

``` js
      var uriHistory = [];
      riot.router.on('route:updated', function() {
         uriHistory.push(riot.router.current.uri);
         if (uriHistory.length > 20) uriHistory.splice(0, 1);
      });
```
