### ISSUE TITLE
dependency on node v4.1.x affects yarn and npm warn

### ISSUE THREAD

**Issue by stukennedy** [gabrielmoreira/riot-router#30]
installing riot-router on versions of node other than 4.1.x causes an NPM warn and stops yarn from being able to install. (has to be used with switch --ignore-engines)
```
npm WARN engine riot-router@0.9.4: wanted: {"node":"~4.1.1"} (current: {"node":"4.5.0","npm":"2.15.9"})
```
Is there a reason why this hard dependency has been included in package.json; should it not be '^4.1.1'?
It seems to work fine on node 4.5.x if the warnings are ignored.

**Comment by gabrielmoreira** [comment]
@continuata Thank you!

Riot-Router 0.9.5 released removing this dependency.
