### ISSUE TITLE
Update URL on redirect

### ISSUE THREAD

**Issue by danhper** [gabrielmoreira/riot-router#8]
The current implementation of `redirect` changes the rendered content, but does not
do anything about the URL. I think in most use cases, having the URL updated
is quite important to keep the displayed page and the URL consistent.

It should be quite easy to do by changing `Router.processRedirect` to call `riot.route` instead of recursing on `this.processRequest`. `Router.process` would then be executed again with the new uri.
Infinite redirect could possibly be checked in `Context.redirectTo` by comparing the current uri and the target uri.

What do you think?

**Comment by gabrielmoreira** [comment]
@tuvistavie 

I think it's a excelent suggestion. 

It's done, thank you.

**Comment by danhper** [comment]
Great, thanks!
