### ISSUE TITLE
Subroute rerenders parent route

### ISSUE THREAD

**Issue by ghost** [gabrielmoreira/riot-router#9]
When visiting a subroute, the parent route rerenders.

Example:
1. Visit /users
2. Visit /users/show/1

This causes for example forms to lose their data. Could be an issue when using a sort / search on the parent, then showing a modal for the detailview.

Is there any way to fix this? Or should I use a different approach?

**Comment by gabrielmoreira** [comment]
@dennisver Hi. 

Can you provide some sample to better illustrate your point?

One way is using this.on('unmount', saveYourStateFunction); and this.on('mount', loadYourStateFunction);

If it is really necessary, i think we can bypass rerender on method mountTag of route tag:
https://github.com/gabrielmoreira/riot-router/blob/master/router.js#L327
But we'll need to compare current route tag, and current route api object (deep compare). This can be optional, like using some <route reuseTags={true}/>.

**Comment by gabrielmoreira** [comment]
Or... we can update tag instance if is the same tag...

**Comment by gabrielmoreira** [comment]
@dennisver,

Now we can flag updatable routes with `new Route({tag: 'users', updatable:true})`, or for all routes
`riot.router.config.updatable = true`

Working on Riot-Router 0.7.0.

You can test at http://gabrielmoreira.github.io/riot-router/examples/example-01.html#/users/top
Just filter an user, and click on user to show user detail.

**Comment by ghost** [comment]
Looks like a good solution, thanks!
